# Generated by Django 4.2.6 on 2023-10-23 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0004_item_delete_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FoodItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='FoodMenus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Menus',
                'ordering': ('name',),
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='foodcategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_django_app.foodmenus'),
        ),
        migrations.AddField(
            model_name='foodcategories',
            name='foodmenu_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_django_app.foodmenus'),
        ),
    ]
