# Generated by Django 4.2.6 on 2023-10-23 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0005_foodcategories_fooditems_foodmenus_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditems',
            name='foodcategory_id',
        ),
        migrations.DeleteModel(
            name='FoodCategories',
        ),
        migrations.DeleteModel(
            name='FoodItems',
        ),
    ]
