# Generated by Django 4.2.6 on 2023-10-23 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0008_foodcategories_fooditems_foodmenus_delete_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='foodcategory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_django_app.foodcategories'),
        ),
    ]
