# Generated by Django 4.2.6 on 2023-10-23 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0009_alter_fooditems_foodcategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategories',
            old_name='foodmenu_id',
            new_name='foodmenu',
        ),
        migrations.RenameField(
            model_name='fooditems',
            old_name='foodcategory_id',
            new_name='foodcategory',
        ),
    ]
