# Generated by Django 4.2.6 on 2023-10-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0010_rename_foodmenu_id_foodcategories_foodmenu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcategories',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='tag',
            field=models.CharField(default=12, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodmenus',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
