# Generated by Django 4.2.6 on 2023-10-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0011_foodcategories_published_fooditems_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.FloatField(),
        ),
    ]
