# Generated by Django 4.2.6 on 2023-10-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0013_rename_foodmenu_foodcategories_foodmenu_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategories',
            old_name='foodmenu_id',
            new_name='foodmenu',
        ),
    ]
