# Generated by Django 4.2.6 on 2023-10-25 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0015_alter_fooditems_foodcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategories',
            name='foodmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_django_app.foodmenus'),
        ),
    ]
