# Generated by Django 4.2.6 on 2023-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0019_foodcategories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/admin/categories'),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/admin/items'),
        ),
    ]
