# Generated by Django 4.2.6 on 2023-10-26 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0021_alter_foodcategories_foodmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategories',
            name='foodmenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_django_app.foodmenus'),
        ),
        migrations.AlterField(
            model_name='foodcategories',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
