# Generated by Django 4.2.6 on 2023-10-27 02:10

from django.db import migrations, models
import my_django_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0022_alter_foodcategories_foodmenu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=my_django_app.models.upload_to),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/item'),
        ),
    ]
