# Generated by Django 4.2.6 on 2023-10-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0023_alter_foodcategories_image_alter_fooditems_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcategories',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='foodmenus',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
