# Generated by Django 4.2.6 on 2023-10-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0025_alter_fooditems_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='table/qrcode')),
                ('status', models.CharField(max_length=128)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Items',
                'ordering': ('name',),
            },
        ),
    ]
