# Generated by Django 4.2.6 on 2023-10-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0025_alter_fooditems_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.RemoveField(
            model_name='fooditems',
            name='tag',
        ),
        migrations.AddField(
            model_name='fooditems',
            name='tag',
            field=models.ManyToManyField(to='my_django_app.tag'),
        ),
    ]
