# Generated by Django 4.2.6 on 2023-10-30 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0026_tag_alter_fooditems_price_remove_fooditems_tag_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='FoodTags',
        ),
        migrations.AlterModelOptions(
            name='fooditems',
            options={'ordering': ('name',), 'verbose_name_plural': 'Tags'},
        ),
    ]
