# Generated by Django 4.2.6 on 2023-10-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0026_ordertables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertables',
            options={'ordering': ('name',), 'verbose_name_plural': 'QRtable'},
        ),
    ]
