# Generated by Django 4.2.6 on 2023-10-30 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0027_rename_tag_foodtags_alter_fooditems_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcategories',
            options={'ordering': ('id',), 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='fooditems',
            options={'ordering': ('id',), 'verbose_name_plural': 'Items'},
        ),
        migrations.AlterModelOptions(
            name='foodmenus',
            options={'ordering': ('id',), 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='foodtags',
            options={'ordering': ('name',), 'verbose_name_plural': 'Tags'},
        ),
    ]
