# Generated by Django 4.2.6 on 2023-11-06 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0027_alter_ordertables_options'),
        ('my_django_app', '0028_alter_foodcategories_options_alter_fooditems_options_and_more'),
    ]

    operations = [
    ]
