# Generated by Django 4.2.6 on 2023-11-08 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0029_merge_20231106_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditems',
            old_name='foodcategory',
            new_name='foodcategory_id',
        ),
    ]
