# Generated by Django 4.2.6 on 2023-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0031_alter_fooditems_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodcategories',
            old_name='foodmenu',
            new_name='foodmenu_id',
        ),
        migrations.AlterField(
            model_name='fooditems',
            name='tag',
            field=models.ManyToManyField(blank=True, to='my_django_app.foodtags'),
        ),
    ]
