# Generated by Django 4.2.6 on 2023-11-11 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0029_merge_20231106_1150'),
        ('my_django_app', '0032_rename_foodmenu_foodcategories_foodmenu_id_and_more'),
    ]

    operations = [
    ]
