# Generated by Django 4.2.6 on 2023-11-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0033_merge_20231111_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Variants',
            },
        ),
        migrations.AlterModelOptions(
            name='foodtags',
            options={'ordering': ('id',), 'verbose_name_plural': 'Tags'},
        ),
    ]
