# Generated by Django 4.2.6 on 2023-11-14 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0035_alter_variants_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variants',
            options={'ordering': ('id',), 'verbose_name_plural': 'Variants'},
        ),
    ]
