# Generated by Django 4.2.6 on 2023-11-14 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0037_variantvalues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantvalues',
            options={'ordering': ('id',), 'verbose_name_plural': 'Variants Value'},
        ),
        migrations.RenameField(
            model_name='variantvalues',
            old_name='variant',
            new_name='title',
        ),
    ]
