# Generated by Django 4.2.6 on 2023-11-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0038_alter_variantvalues_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Variants',
            new_name='VariantGroups',
        ),
        migrations.AlterModelOptions(
            name='variantgroups',
            options={'ordering': ('id',), 'verbose_name_plural': 'Variant Group'},
        ),
    ]
