# Generated by Django 4.2.6 on 2023-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0039_rename_variants_variantgroups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantvalues',
            name='title',
            field=models.ManyToManyField(to='my_django_app.variantgroups'),
        ),
    ]
