# Generated by Django 4.2.6 on 2023-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0040_alter_variantvalues_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantvalues',
            options={'ordering': ('id',), 'verbose_name_plural': 'Variant Value'},
        ),
        migrations.AddField(
            model_name='variantgroups',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variantvalues',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
