# Generated by Django 4.2.6 on 2023-11-20 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0041_alter_variantvalues_options_variantgroups_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantvalues',
            name='title',
        ),
        migrations.AddField(
            model_name='variantvalues',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_django_app.variantgroups'),
        ),
    ]
