# Generated by Django 4.2.6 on 2023-11-21 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0042_remove_variantvalues_title_variantvalues_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantvalues',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='my_django_app.variantgroups'),
            preserve_default=False,
        ),
    ]
