# Generated by Django 4.2.6 on 2023-11-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_app', '0043_alter_variantvalues_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertables',
            name='link',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
